name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - seaborn
  - cartopy
  - geopandas
  - requests
  - scipy
  - pip:
    - pandas
    - matplotlib
    - svgpath2mpl
    - wasabi>=0.2.1,<1.1.0
    - black==19.10b0
